name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: pnpm install
      - run: pnpm run lint --if-present
      - run: pnpm run prettier:check --if-present
      - run: pnpm test
      - run: pnpm run build --if-present
